[build]
  command = "npx @11ty/eleventy"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"

# --- ADIÇÃO IMPORTANTE PARA O CÉREBRO (FUNCTIONS) ---
[functions]
  directory = "netlify/functions"
